# Generated by Django 4.1.5 on 2023-01-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='age',
            field=models.IntegerField(),
        ),
    ]
